sudo: required

services:
  - docker

before_install:
  - docker build -t Dockertravisci -f Dockerfile.dev .

script:
   - docker run -e CI=true Dockertravisci npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: "eu-north-1"
  app: "docker-travisci"
  env: "Docker-travisci-env"
  bucket_name: "elasticbeanstalk-eu-north-1-356725175292"
  bucket_path: "docker-travisci"
  on:
    branch: master